### ISSUE TITLE
Update Account State to hold numerical models for balances instead of strings

### ISSUE THREAD

**Issue by saltyskip** [CityOfZion/neo-swift#29]
Although RPC server returns strings we should convert them to doubles/ints no matter what

**Comment by lm2s** [comment]
You can assign this to me.

**Comment by lm2s** [comment]
Regarding the AssetState struct, `amount` and `available` should be equivalent to C# `long` which is a `Int64`. In Swift, `Int` defaults to `Int32` or `Int64` according to the platform it's running on.

So for iOS it'll be `Int64` and is not an issue.

But should we take into account supporting other platforms (future-wise)? (By this I mean specifically declaring `Int64` instead of `Int`.)
